name: Shakti-Final-Strike
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Overwrite and Build
        run: |
          # Purani files ka asar khatam karna
          rm -f build.gradle settings.gradle
          echo "plugins { id 'com.android.application' version '8.2.2' apply false }" > build.gradle
          echo "include ':app'" > settings.gradle
          # Naya Gradle Setup
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Airawat-Success-APK
          path: "**/*.apk"
          
