name: Shakti-APK-Build
on: [push, workflow_dispatch]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Replace Old Configs
        run: |
          # Puraani repositories ko hata kar nayi repositories daalna
          echo "buildscript { repositories { google(); mavenCentral() }; dependencies { classpath 'com.android.tools.build:gradle:8.2.2' } }" > build.gradle
          echo "allprojects { repositories { google(); mavenCentral() } }" >> build.gradle
          # Gradle Wrapper update
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
      - name: Build With No Lint
        run: ./gradlew assembleDebug -x lint -x test --stacktrace --no-daemon
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Shakti-Final-Success
          path: "**/*.apk"
          
